export const GET_LIST_CART_ITEM_REQUEST = `GET_LIST_CART_ITEM_REQUEST`;
export const GET_LIST_CART_ITEM_SUCCESS = `GET_LIST_CART_ITEM_SUCCESS`;
export const GET_LIST_CART_ITEM_FAILED = `GET_LIST_CART_ITEM_FAILED`;
export const GET_LIST_PRODUCT_REQUEST = `GET_LIST_PRODUCT_REQUEST`;
export const GET_LIST_PRODUCT_SUCCESS = `GET_LIST_PRODUCT_SUCCESS`;
export const GET_LIST_PRODUCT_FAILED = `GET_LIST_PRODUCT_FAILED`;
